import { NavMenu } from '@/components/NavMenu/NavMenu';
import './globals.css';
import type { Metadata } from 'next';
import AuthProvider from '@/providers/AuthProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang='en'>
        <body>
          <NavMenu />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
